[package]
name = "day3"
version = "0.1.0"
authors = ["Alec Snyder <linuxbash8@gmail.com>"]
edition = "2018"

[dependencies]
util = { path = "../util" }

[[bin]]
name = "main1"
path = "src/main1.rs"

[[bin]]
name = "main2"
path = "src/main2.rs"
